apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: echoserver
      containers:
      - name: echoserver
        image: cilium/echoserver:1.10.3
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-local
  labels:
    svc: echoserver
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: echoserver
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-cluster
  labels:
    svc: echoserver
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: echoserver
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443